import React, { useState, useEffect } from 'react';
import { Sparkles, Brain, Code, Terminal, Play, RotateCw, MessagesSquare, Compass, ShieldAlert, Target } from 'lucide-react';
import { sound } from '../sound';
import { AIQuest, NPCDialogue, ThemeType } from '../types';

interface AIGeneratorDshProps {
  quest: AIQuest | null;
  onRefreshQuest: () => void;
  onPlayGeneratedLevel: (layout: any) => void;
}

export default function AIGeneratorDsh({ quest, onRefreshQuest, onPlayGeneratedLevel }: AIGeneratorDshProps) {
  // Level parameters
  const [theme, setTheme] = useState<ThemeType>('forest');
  const [difficulty, setDifficulty] = useState<'easy' | 'medium' | 'hard'>('medium');
  const [length, setLength] = useState<'short' | 'medium' | 'long'>('medium');
  const [isGenerating, setIsGenerating] = useState(false);
  const [logMessages, setLogMessages] = useState<string[]>([]);
  const [completionPercent, setCompletionPercent] = useState(0);

  // NPC dialogue state
  const [npcName, setNpcName] = useState('Old Shopkeeper');
  const [npcPersonality, setNpcPersonality] = useState('Funny and Wise');
  const [npcDialogue, setNpcDialogue] = useState<NPCDialogue | null>({
    greeting: "Ho-ho! Welcome, traveller! Fancy some pixel secrets?",
    hint: "If you dash right as you jump, you can clear the spikes in World 2 easily!",
    farewell: "Stay safe out there! Watch your step, gravity is a cruel mistress."
  });
  const [isGeneratingNpc, setIsGeneratingNpc] = useState(false);

  // Auto scroll logs
  useEffect(() => {
    let interval: any;
    if (isGenerating) {
      setCompletionPercent(5);
      setLogMessages([
        "> Accessing Google Gemini Cloud Model...",
        "> Initializing level structural geometry...",
      ]);
      
      const phrases = [
        "> Building safe spawn point at X: 0 to 400...",
        "> Placing theme-specific blocks: " + theme.toUpperCase() + " material veins...",
        "> Seeding collectibles, star crystals, and chests...",
        "> Simulating block layout collision paths...",
        "> Plotting enemy patrol nodes and trigger AI states...",
        "> Generating game objective gateway star portal...",
        "> Packaging platform layout to custom 2D JSON data...",
        "> Finalizing metadata and verifying level consistency..."
      ];

      let step = 0;
      interval = setInterval(() => {
        if (step < phrases.length) {
          setLogMessages(prev => [...prev, phrases[step]]);
          setCompletionPercent(prev => Math.min(prev + 11, 95));
          step++;
        } else {
          setCompletionPercent(100);
          clearInterval(interval);
        }
      }, 500);
    }
    return () => clearInterval(interval);
  }, [isGenerating, theme]);

  const handleGenerateLevel = async () => {
    sound.playPowerUp();
    setIsGenerating(true);
    setCompletionPercent(0);

    try {
      const response = await fetch('/api/generate-level', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ theme, difficulty, length })
      });

      const layout = await response.json();
      setIsGenerating(false);
      sound.playVictory();
      onPlayGeneratedLevel(layout);
    } catch (e) {
      console.error(e);
      setIsGenerating(false);
    }
  };

  const handleGenerateNpcDialogue = async () => {
    sound.playCoin();
    setIsGeneratingNpc(true);
    try {
      const response = await fetch('/api/generate-npc', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name: npcName, world: theme, personality: npcPersonality })
      });
      const data = await response.json();
      setNpcDialogue(data);
      sound.playPowerUp();
    } catch (e) {
      console.error(e);
    } finally {
      setIsGeneratingNpc(false);
    }
  };

  const handleQuestGenerate = () => {
    sound.playCoin();
    onRefreshQuest();
  };

  return (
    <div className="space-y-8 max-w-5xl mx-auto text-white font-sans">
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Left Column: Generator controls */}
        <div className="lg:col-span-2 bg-zinc-950 border-4 border-zinc-700 p-6 rounded-lg shadow-2xl relative overflow-hidden">
          <div className="absolute top-0 right-0 p-3 opacity-10">
            <Brain className="w-40 h-40 text-yellow-400" />
          </div>

          <div className="flex items-center gap-3 border-b-4 border-zinc-800 pb-3 mb-6">
            <Sparkles className="w-8 h-8 text-yellow-400 animate-pulse" />
            <div>
              <h2 className="text-2xl font-mono text-yellow-400 font-extrabold uppercase">AI Sandbox Architect</h2>
              <p className="text-xs text-zinc-400 font-mono">Create infinite retro levels generated by Gemini</p>
            </div>
          </div>

          {isGenerating ? (
            /* Sci-fi scrolling code loading screen */
            <div className="bg-zinc-950 border-2 border-green-500/30 p-6 rounded-lg font-mono text-xs text-green-400 space-y-4 min-h-[360px] flex flex-col justify-between">
              <div>
                <div className="flex justify-between items-center border-b border-green-500/20 pb-2 mb-3">
                  <div className="flex items-center gap-2">
                    <Terminal className="w-4 h-4 animate-pulse" />
                    <span className="font-bold text-green-400 uppercase tracking-widest">GEMINI COMPILING STAGE</span>
                  </div>
                  <span className="animate-pulse">{completionPercent}%</span>
                </div>
                <div className="space-y-2 h-[220px] overflow-y-auto pr-2 custom-scrollbar flex flex-col justify-end">
                  {logMessages.map((msg, i) => (
                    <div key={i} className="leading-relaxed text-[11px] font-mono tracking-tight text-green-300">
                      {msg}
                    </div>
                  ))}
                  <div className="h-1 bg-zinc-900 rounded-full mt-2 overflow-hidden border border-green-950">
                    <div className="h-full bg-green-500 transition-all duration-300" style={{ width: `${completionPercent}%` }} />
                  </div>
                </div>
              </div>
              <div className="text-right text-green-500 text-[10px] uppercase">
                Constructing platform matrix... please stand by
              </div>
            </div>
          ) : (
            <div className="space-y-6">
              {/* Theme selection */}
              <div>
                <label className="block text-xs font-mono font-bold uppercase tracking-wider text-zinc-400 mb-2">Select Theme</label>
                <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
                  {[
                    { id: 'forest', label: 'Forest Grass', color: 'border-emerald-600 bg-emerald-950/20 text-emerald-300 hover:bg-emerald-950/40' },
                    { id: 'desert', label: 'Desert Sand', color: 'border-amber-600 bg-amber-950/20 text-amber-300 hover:bg-amber-950/40' },
                    { id: 'ice', label: 'Ice Peaks', color: 'border-cyan-600 bg-cyan-950/20 text-cyan-300 hover:bg-cyan-950/40' },
                    { id: 'volcano', label: 'Volcano Core', color: 'border-red-600 bg-red-950/20 text-red-300 hover:bg-red-950/40' },
                    { id: 'sky', label: 'Sky Castle', color: 'border-violet-600 bg-violet-950/20 text-violet-300 hover:bg-violet-950/40' }
                  ].map((t) => (
                    <button
                      key={t.id}
                      onClick={() => { sound.playCoin(); setTheme(t.id as any); }}
                      className={`py-2 px-1 border-2 text-xs font-mono font-bold uppercase rounded-md text-center cursor-pointer transition ${t.color} ${
                        theme === t.id ? 'border-yellow-400 ring-2 ring-yellow-400/30' : ''
                      }`}
                    >
                      {t.label}
                    </button>
                  ))}
                </div>
              </div>

              {/* Difficulty and Length */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                <div>
                  <label className="block text-xs font-mono font-bold uppercase tracking-wider text-zinc-400 mb-2">Stage Difficulty</label>
                  <div className="flex gap-2">
                    {['easy', 'medium', 'hard'].map((diff) => (
                      <button
                        key={diff}
                        onClick={() => { sound.playCoin(); setDifficulty(diff as any); }}
                        className={`flex-1 py-1.5 px-3 border-2 text-xs font-mono font-bold uppercase rounded-md text-center cursor-pointer transition ${
                          difficulty === diff
                            ? 'border-yellow-400 bg-zinc-900 text-yellow-300'
                            : 'border-zinc-800 bg-zinc-950 text-zinc-500 hover:border-zinc-700'
                        }`}
                      >
                        {diff}
                      </button>
                    ))}
                  </div>
                </div>

                <div>
                  <label className="block text-xs font-mono font-bold uppercase tracking-wider text-zinc-400 mb-2">Stage Length</label>
                  <div className="flex gap-2">
                    {['short', 'medium', 'long'].map((len) => (
                      <button
                        key={len}
                        onClick={() => { sound.playCoin(); setLength(len as any); }}
                        className={`flex-1 py-1.5 px-3 border-2 text-xs font-mono font-bold uppercase rounded-md text-center cursor-pointer transition ${
                          length === len
                            ? 'border-yellow-400 bg-zinc-900 text-yellow-300'
                            : 'border-zinc-800 bg-zinc-950 text-zinc-500 hover:border-zinc-700'
                        }`}
                      >
                        {len}
                      </button>
                    ))}
                  </div>
                </div>
              </div>

              <button
                onClick={handleGenerateLevel}
                className="w-full mt-6 py-4 px-6 bg-yellow-500 hover:bg-yellow-400 text-zinc-950 font-mono text-base font-extrabold uppercase rounded-lg shadow-lg flex items-center justify-center gap-3 transition cursor-pointer border-b-4 border-yellow-700 active:border-b-0 active:translate-y-1"
              >
                <Brain className="w-5 h-5" /> Assemble AI Level Layout
              </button>
            </div>
          )}
        </div>

        {/* Right Column: AI Quest details */}
        <div className="bg-zinc-900 border-4 border-zinc-700 p-6 rounded-lg flex flex-col justify-between">
          <div>
            <div className="flex items-center gap-2 border-b-4 border-zinc-800 pb-3 mb-4">
              <Compass className="w-6 h-6 text-cyan-400" />
              <h3 className="font-mono text-base font-extrabold text-cyan-400 uppercase">Active AI Quest</h3>
            </div>

            {quest ? (
              <div className="space-y-4">
                <div className="bg-zinc-950 p-4 border border-zinc-800 rounded-md">
                  <div className="flex items-center gap-2 mb-2">
                    <Target className="w-5 h-5 text-yellow-400 animate-pulse" />
                    <h4 className="font-mono text-sm font-bold text-zinc-200">{quest.title}</h4>
                  </div>
                  <p className="text-xs text-zinc-400 leading-relaxed font-sans mt-1">
                    {quest.description}
                  </p>
                  
                  {/* Progress bar */}
                  <div className="mt-4">
                    <div className="flex justify-between font-mono text-[10px] text-zinc-500 mb-1">
                      <span>PROGRESS</span>
                      <span>{quest.currentCount} / {quest.targetCount}</span>
                    </div>
                    <div className="h-2 bg-zinc-900 rounded-full overflow-hidden border border-zinc-800">
                      <div 
                        className="h-full bg-cyan-400 transition-all duration-300" 
                        style={{ width: `${Math.min(100, (quest.currentCount / quest.targetCount) * 100)}%` }} 
                      />
                    </div>
                  </div>
                </div>

                <div className="bg-zinc-800/50 p-3 rounded border border-zinc-700 flex items-center justify-between text-xs font-mono">
                  <span className="text-zinc-500 uppercase">REWARD:</span>
                  <span className="text-yellow-400 font-bold uppercase">{quest.rewardCoins} GOLD COINS</span>
                </div>
              </div>
            ) : (
              <p className="text-xs text-zinc-500 font-mono">No active quest loaded. Touch Refresh below.</p>
            )}
          </div>

          <button
            onClick={handleQuestGenerate}
            className="w-full mt-4 py-2 border-2 border-cyan-500/50 hover:bg-cyan-950/20 text-cyan-300 rounded font-mono text-xs uppercase flex items-center justify-center gap-2 transition cursor-pointer"
          >
            <RotateCw className="w-4 h-4" /> Request Random Quest
          </button>
        </div>
      </div>

      {/* NPC Dialogue Interactive Block */}
      <div className="bg-zinc-900 border-4 border-zinc-700 p-6 rounded-lg relative">
        <div className="flex items-center gap-2 border-b-4 border-zinc-800 pb-3 mb-6">
          <MessagesSquare className="w-6 h-6 text-purple-400" />
          <h3 className="font-mono text-sm font-extrabold text-purple-400 uppercase">Interactive NPC Generator</h3>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="space-y-4">
            <div>
              <label className="block text-[11px] font-mono font-bold uppercase text-zinc-400 mb-1">NPC Name</label>
              <select
                value={npcName}
                onChange={(e) => setNpcName(e.target.value)}
                className="w-full bg-zinc-950 text-xs text-zinc-200 border-2 border-zinc-700 rounded px-2.5 py-1.5 focus:border-yellow-400 font-mono uppercase"
              >
                <option value="Old Shopkeeper">Old Shopkeeper</option>
                <option value="Ancient Sage">Ancient Sage</option>
                <option value="Pixel Dragon King">Pixel Dragon King</option>
                <option value="Cosmic Astronaut">Cosmic Astronaut</option>
                <option value="Grumpy Goblin">Grumpy Goblin</option>
              </select>
            </div>

            <div>
              <label className="block text-[11px] font-mono font-bold uppercase text-zinc-400 mb-1">Personality</label>
              <select
                value={npcPersonality}
                onChange={(e) => setNpcPersonality(e.target.value)}
                className="w-full bg-zinc-950 text-xs text-zinc-200 border-2 border-zinc-700 rounded px-2.5 py-1.5 focus:border-yellow-400 font-mono uppercase"
              >
                <option value="Funny and wise">Funny & Wise</option>
                <option value="Sarcastic and irritable">Sarcastic & Irritable</option>
                <option value="Hyperactive and positive">Overly Energetic</option>
                <option value="Mysterious and quiet">Mysterious & Quiet</option>
              </select>
            </div>

            <button
              onClick={handleGenerateNpcDialogue}
              disabled={isGeneratingNpc}
              className="w-full py-2 bg-purple-700 hover:bg-purple-600 text-white font-mono text-xs font-bold uppercase rounded cursor-pointer flex items-center justify-center gap-2 transition"
            >
              <Sparkles className="w-4 h-4" /> {isGeneratingNpc ? 'Generating...' : 'Update Dialogue'}
            </button>
          </div>

          <div className="md:col-span-2 space-y-4">
            {npcDialogue && (
              <div className="bg-zinc-950 p-4 border border-zinc-800 rounded-lg space-y-3 relative font-sans">
                {/* 2012 bubble layout */}
                <div className="bg-zinc-900 border-2 border-zinc-700 p-3 rounded-lg relative">
                  <span className="absolute -top-2.5 left-3 px-1.5 bg-yellow-500 text-zinc-950 font-mono text-[9px] font-bold uppercase rounded">
                    {npcName} greets you
                  </span>
                  <p className="text-xs text-zinc-200 italic font-mono mt-1">
                    "{npcDialogue.greeting}"
                  </p>
                </div>

                <div className="bg-zinc-90 w border-2 border-zinc-700 p-3 rounded-lg relative">
                  <span className="absolute -top-2.5 left-3 px-1.5 bg-cyan-400 text-zinc-950 font-mono text-[9px] font-bold uppercase rounded">
                    Wisdom Hint
                  </span>
                  <p className="text-xs text-zinc-200 italic font-mono mt-1">
                    "{npcDialogue.hint}"
                  </p>
                </div>

                <div className="bg-zinc-900 border-2 border-zinc-700 p-3 rounded-lg relative">
                  <span className="absolute -top-2.5 left-3 px-1.5 bg-zinc-500 text-white font-mono text-[9px] font-bold uppercase rounded">
                    Parting Words
                  </span>
                  <p className="text-xs text-zinc-300 italic font-mono mt-1">
                    "{npcDialogue.farewell}"
                  </p>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
